import type { Metadata } from "next";
import { Smythe } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const smythe = Smythe({
  weight: "400",
  variable: "--font-smythe",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "LesFlashcards - LesFichesMémoire",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${smythe.variable} ${smythe.variable} antialiased`}
      >
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
